### ISSUE TITLE
Error: file 'nixpkgs' was not found in the Nix search path

### ISSUE THREAD

**Issue by arximboldi** [nixbuild/nix-quick-install-action#3]
I am using the action with:
```
      - uses: nixbuild/nix-quick-install-action@v2
```
However, I get this error:
```
error: file 'nixpkgs' was not found in the Nix search path
```
Is there anything I am doing wrong?

**Comment by rickynils** [comment]
As stated in https://github.com/marketplace/actions/nix-quick-install#details, this action doesn't set up NIX_PATH or Nix channels, so you have to do that on your own.

There's a number of different ways to handle this in Nix. For example, you can assign [NIX_PATH](https://nixos.org/manual/nix/stable/#env-NIX_PATH), [pin nixpkgs](https://nixos.wiki/wiki/FAQ/Pinning_Nixpkgs) or use [flakes](https://www.tweag.io/blog/2020-05-25-flakes/).

**Comment by arximboldi** [comment]
Thank you a lot for the answer @rickynils and sorry for the misunderstanding!

**Comment by afreakk** [comment]
I've pinned nixpkgs  in my shell.nix, but it seems the `import nix/sources.nix;` causes issues.

```
error:
       … while calling the 'import' builtin

         at «string»:1:2:

            1| (import <nixpkgs> {}).bashInteractive
             |  ^

       … while realising the context of a path

       … while calling the 'findFile' builtin

         at «string»:1:9:

            1| (import <nixpkgs> {}).bashInteractive
             |         ^

       error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```
