### ISSUE TITLE
How do you use this without flakes?

### ISSUE THREAD

**Issue by anka-213** [nixbuild/nix-quick-install-action#35]
I get this error when I try using the latest version without flakes:

```
Run nixbuild/nix-quick-install-action@v25
Run /home/runner/work/_actions/nixbuild/nix-quick-install-action/v25/nix-quick-install.sh
/*stdin*\           : 8[7](https://github.com/anka-213/gf-lsp/actions/runs/5858046239/job/15881637273#step:3:8)746560 bytes 
installing 'nix-2.16.1'
building '/nix/store/yx8dlip6m5lb4s9pl0693abpsalr78ga-user-environment.drv'...
Run /home/runner/work/_actions/nixbuild/nix-quick-install-action/v25/read-nix-config-from-flake.sh
+ jq -r '.content|gsub("[\n\t]"; "")|@base64d'
+ gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: [20](https://github.com/anka-213/gf-lsp/actions/runs/5858046239/job/15881637273#step:3:22)22-11-28' '/repos/anka-213/gf-lsp/contents/flake.nix?ref=f60fce4a36646e06b70[31](https://github.com/anka-213/gf-lsp/actions/runs/5858046239/job/15881637273#step:3:34)fa48fb2ab16cebf2074'
gh: Not Found (HTTP 404)
jq: error (at <stdin>:0): null (null) cannot be matched, as it is not a string
```

Here's the full log: https://github.com/anka-213/gf-lsp/actions/runs/5858267269/job/15881863895

**Comment by rickynils** [comment]
Hmm, this looks bad, thanks for reporting it. Can you work around it by setting [load_nixConfig](https://github.com/nixbuild/nix-quick-install-action/blob/1d74a69e98e9900ecca9e222c1310c456d4def0e/action.yml#L48) to `false`?

**Comment by rickynils** [comment]
cc @blaggacao

**Comment by blaggacao** [comment]
I see. At the point of hitting this error, we probably have at least a config drift, but we could fail much more gracefully.

Wdyt?

**Comment by develop7** [comment]
> Hmm, this looks bad, thanks for reporting it. Can you work around it by setting [load_nixConfig](https://github.com/nixbuild/nix-quick-install-action/blob/1d74a69e98e9900ecca9e222c1310c456d4def0e/action.yml#L48) to `false`?

Tried this too, doesn't help

Any suggestions?

**Comment by jgoux** [comment]
Hello, I'm hitting the same issue [here](https://github.com/jgoux/acme/actions/runs/6622801204?pr=25).

I'd love to be able to use `nix-quick-install-action` in order to leverage [cache-nix-action](https://github.com/nix-community/cache-nix-action), which seem to require this specific package to work.

**Comment by rickynils** [comment]
@jgoux Could you try using the latest revision (`nix-quick-install-action@master`)? I just committed a couple of fixes. It would be ideal if you could try it out both with `load_nixConfig` set to `false` and `true`.

**Comment by jgoux** [comment]
@rickynils I just tried against `nix-quick-install-action@master`, it seems to work with the option `load_nixConfig` set to `false`. I tried `true` and got the same error as before. 👍

Thanks for the reactivity!

**Comment by jgoux** [comment]
@rickynils The output is here: https://github.com/jgoux/acme/actions/runs/6623591526/job/17990926008#step:3:52

**Comment by rickynils** [comment]
@jgoux Would you mind re-running that workflow with `load_nixConfig = true` again?

**Comment by jgoux** [comment]
@rickynils It's now working with `load_nixConfig = true`! Great job! https://github.com/jgoux/acme/actions/runs/6624474804/job/17993531555?pr=25#step:3:34

**Comment by rickynils** [comment]
Fixed in [v26](https://github.com/nixbuild/nix-quick-install-action/releases/tag/v26)
