### ISSUE TITLE
Using it on a runner hosted on an arm Raspberry Pi

### ISSUE THREAD

**Issue by hannesa2** [nixbuild/nix-quick-install-action#39]
Hi, when i use this action on Raspberry Pi (arm64) I run into 
<img width="1108" alt="image" src="https://github.com/PostgREST/postgrest/assets/3314607/aa559bd9-8de8-4158-ae58-523bda041cf6">

https://github.com/hannesa2/postgrest/actions/runs/7083794458/job/19277085219

Do you have any clue how to get rid of it ?

**Comment by rickynils** [comment]
`linux-aarch64` runners are not supported, since they are not (yet) available as hosted GitHub Actions runners. I believe that with the latest [release](https://github.com/nixbuild/nix-quick-install-action/releases/tag/v29) you will now get a more descriptive error message.
